so ~/vimrc/general_setup.vim
so ~/vimrc/search_setup.vim
so ~/vimrc/lsp_setup.vim
so ~/vimrc/wsl2_setup.vim
so ~/vimrc/theme_setup.vim
so ~/vimrc/easy_motion_setup.vim
so ~/vimrc/custom_vim_mappings_setup.vim
so ~/vimrc/comment_setup.vim
so ~/vimrc/auto_setup.vim
so ~/vimrc/browser_actions_setup.vim
